(function(){
    Config = {
		IMG_BASE_DIR: '../things_images/',
		IMG_FILE_EXTENSION: '.jpg',
		IMG_FULLSIZE_FILENAME_SUFFIX: 'L',
		NUM_IMAGES_PER_GROUP: 16,
		NUM_IMAGE_GROUPS: 19,
    NUM_IMAGE_GROUPS_PER_LOGIN: 5,
    NUM_IMAGE_GROUPS_PER_PORTFOLIO: 10
	};
})();
